-- Full CREATE TABLE for updated quotations table (2024-07-10)
CREATE TABLE `quotations` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `quote_id` varchar(50) NOT NULL,
  `customer_name` varchar(100) NOT NULL,
  `customer_email` varchar(100) DEFAULT NULL,
  `customer_phone` varchar(20) NOT NULL,
  `customer_location` varchar(50) DEFAULT NULL,
  `service_level` varchar(50) DEFAULT NULL,
  `material_source` varchar(50) DEFAULT NULL,
  `material_type` varchar(50) DEFAULT NULL,
  `material_color` varchar(100) DEFAULT NULL,
  `worktop_layout` varchar(50) DEFAULT NULL,
  `project_type` varchar(100) DEFAULT NULL,
  `timeline` varchar(50) DEFAULT NULL,
  `sink_option` varchar(100) DEFAULT NULL,
  `additional_comments` text DEFAULT NULL,
  `quote_data` json NOT NULL,
  `pricing_data` json DEFAULT NULL,
  `total_area` decimal(10,4) DEFAULT NULL,
  `total_amount` decimal(12,2) DEFAULT NULL,
  `currency` varchar(3) DEFAULT 'AED',
  `status` enum('pending','reviewed','approved','rejected','completed') DEFAULT 'pending',
  `pdf_generated` tinyint(1) DEFAULT 0,
  `pdf_path` varchar(255) DEFAULT NULL,
  `admin_notes` text DEFAULT NULL,
  `follow_up_date` date DEFAULT NULL,
  `created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `quote_id` (`quote_id`),
  KEY `idx_customer_email` (`customer_email`),
  KEY `idx_status` (`status`),
  KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 